<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="qainfotech-Latitude-3490" ignored="0" name="Test1" tests="3" failures="1" timestamp="25 Aug 2021 01:16:16 GMT" time="0.058" errors="0">
  <testcase name="test" time="0.016" classname="com.dhruv.test.testFlakey.testPackage.Test2">
    <failure type="java.lang.AssertionError" message="Assertion Falied: Second test failed expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: Assertion Falied: Second test failed expected [2] but found [1]
at com.dhruv.test.testFlakey.testPackage.Test2.test(Test2.java:9)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="0.002" classname="com.dhruv.test.testFlakey.testPackage.Test1"/>
  <testcase name="test" time="0.001" classname="com.dhruv.test.testFlakey.testPackage.Test3"/>
</testsuite> <!-- Test1 -->
